# Generated by Django 5.1.5 on 2025-01-28 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SpotifyMockAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="song_details",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="SpotifyMockAPI.songdetails",
            ),
        ),
    ]
