# Generated by Django 5.1.5 on 2025-02-03 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SpotifyMockAPI", "0003_alter_song_song_details"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name="songdetails",
            old_name="durations",
            new_name="duration",
        ),
        migrations.RemoveField(
            model_name="album",
            name="genre",
        ),
        migrations.AddField(
            model_name="song",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pfp",
                    models.ImageField(blank=True, null=True, upload_to="artist_pfp/"),
                ),
                ("label", models.CharField(max_length=255, null=True)),
                ("joined", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="album",
                to="SpotifyMockAPI.artist",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="SpotifyMockAPI.artist",
            ),
        ),
        migrations.AddField(
            model_name="songdetails",
            name="genre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="genre",
                to="SpotifyMockAPI.genre",
            ),
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("public", models.BooleanField(default=True)),
                (
                    "songs",
                    models.ManyToManyField(
                        related_name="playlists", to="SpotifyMockAPI.song"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="library", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="library",
                        to="SpotifyMockAPI.playlist",
                    ),
                ),
            ],
        ),
    ]
